apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cbo-frontend
  name: cbo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbo-frontend
  template:
    metadata:
      labels:
        app: cbo-frontend
    spec:
      containers:
        - image: nexus.labelvie.ma:8012/cbo-frontend
          name: cbo-frontend
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: http://a80748ee3f5ba4e4593a99ea611abdf8-1200620296.us-east-1.elb.amazonaws.com/api/
          ports:
            - containerPort: 3000
              name: http
      imagePullSecrets:
        - name: pullimagedocker
