apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
namespace: fidelite
images:
  - name: nexus.labelvie.ma:8012/cbo-frontend
    newTag: "5536"
