apiVersion: v1
kind: Service
metadata:
  name: cbo-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 3000
  selector:
    app: cbo-frontend
